### ISSUE TITLE
Add Korean translation content and meta entries

### ISSUE THREAD

**Issue by Swader** [status-im/the-explainers#11]
Korean versions of the three two-point-oh posts now exist:

- [ ] Two Point Oh: The Tale of Two Ethers : https://blog.naver.com/status_korea/221448034398

- [ ] Two Point Oh: The Beacon Chain : https://blog.naver.com/status_korea/221447937020

- [ ] Two Point Oh: Explaining Validators : https://blog.naver.com/status_korea/221423804757

All should be turned into MD and added into respective folders, then into the `meta.json` file of each post.
